index:
  path: /inicio
  controller: App\Controller\HomeController::index
animales:
  path: /animales/{nombre}/{apellidos}
  controller: App\Controller\HomeController::animales
  defaults: {nombre: "Sin Nombre", apellidos: "Sin apellidos"}
  methods: [POST,GET]
  requirements:
    nombre: "[A-Z,a-z ]+"     # solo letras
    apellidos: "[A-Z,a-z ]+"  # solo numeros
redirigir:
  path: /redirigir
  controller: App\Controller\HomeController::redirigir
animal_index:
  path: /animal/index
  controller: App\Controller\AnimalController::index
  
animal_save:
  path: /animal/save
  controller: App\Controller\AnimalController::save
  methods: [post]
  
animal_detail:
  path: /animal/{id}
  controller: App\Controller\AnimalController::animal
  
animal_update:
  path: /animal/update/{id}
  controller: App\Controller\AnimalController::update
  
animal_delete:
  path: /animal/delete/{id}
  controller: App\Controller\AnimalController::delete
  
crear_animal:
  path: /crear-animal
  controller: App\Controller\AnimalController::crearAnimal

validar_email:
  path: /validar-email/{email}
  controller: App\Controller\AnimalController::validarEmail

