# se rellena según lexikjwt guia de instalación
security:
    encoders:
        App\Entity\User:
            algorithm: "auto"
            
    providers:
        user_provider:
            id: App\Security\Core\User\UserProvider
            
    firewalls:
        register:
            pattern: ^/api/v1/users/register
            methods: [POST]
            security: false

        login:
            pattern: ^/api/v1/login
            stateless: true
            anonymous: true
            provider: user_provider
            
            # en lugar de json_login que forzaría a enviar los datos de autenticacion en json
            form_login:
                check_path: /api/v1/login_check
                username_parameter: _email
                password_parameter: _password
                # ruta real: vendor/lexik/jwt-authentication-bundle/Security/Http/Authentication/AuthenticationSuccessHandler.php
                success_handler: lexik_jwt_authentication.handler.authentication_success
                # vendor/lexik/jwt-authentication-bundle/Security/Http/Authentication/AuthenticationFailureHandler.php
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                
        api:
            pattern: ^/api/v1
            stateless: true
            guard:
                authenticators:
                    # vendor/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator.php
                    - lexik_jwt_authentication.jwt_token_authenticator
        
    # todo lo que venga despues de /api/v1 tiene que estar autenticado
    access_control:
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }
            